### ISSUE TITLE
Implement CSV Writer and CSV Reader

### ISSUE THREAD

**Issue by artimmeyer** [smn-hrtzsch/SPS#23]
**Explanation**  
Add two files called somewhat like "CSVWriter.cs" and "CSVReader.cs" and implement the associated functionality. 

**Tasks**  
  - [x] Create "CSVWriter.cs" and implement the class functionality
  - [x] Create "CSVReader.cs" and implement the class funtionality
  - [x] Create folders for CSV-files in the project file structure 

**Location**  
The Csharp files should be added to the classlib. 
For the CSV-files create new folder in the SPS-directory.

**GitHub location**  
New branch at first and then pull-request with a review request.
