### ISSUE TITLE
Fix build issues

### ISSUE THREAD

**Issue by smn-hrtzsch** [smn-hrtzsch/SPS#27]
**Explanation**  
Fix the build issues, which result from the incomplete class structure

**Tasks**  
  - [ ] delete unnecessary functions
  - [ ] give return values where needed
  - [ ] look for typos

**Location**  
on new branch build-fix

**GitHub location**  
push the new branch build-fix
