### ISSUE TITLE
Implement CI Email Pipeline

### ISSUE THREAD

**Issue by artimmeyer** [smn-hrtzsch/SPS#42]
**Explanation**  
- Implementation of a working Email-service Continuous Integration pipeline. 
- The program used in the pipeline well be separate from the main program.
- A new folder and Program.cs file are already existing. 

**Tasks**  
  - [x] Simulate member data in the main of "Program.cs" to test the implementation
  - [x] configure "emailroutine-daily-and-weekly.yaml" for the CI pipeline
  - [ ] implement the pipeline using the "CSVReadMemberData.cs" static functions
  - [x] Remove personal addressing in email newsletter (generalization)

**Location**  
- new (local) emailservice Branch
- "Program.cs" as the main that's going to be called from the CI-runner

**GitHub location**  
- push the branch named 'emailservice' from your local machine to the git repo
