### ISSUE TITLE
Implement the Main function of the project

### ISSUE THREAD

**Issue by smn-hrtzsch** [smn-hrtzsch/SPS#45]
**Explanation**  
Implement the logic to run a complete PredictionGame.
Use the implemented functionality of the ClassLib. 

**Tasks**  
  - [ ] Use the CSVWriter and Reader to save and read data for the PredictionGame
  - [ ] Implement the logic to use the console like a menu
  - [ ] make it look nice (e.g. different colors or font sizes in the console)

**Location**  
Modify the Program.cs file in the Program folder of the project.

**GitHub location**  
work on a new branch named 'program' and push the local branch to the github repo.
